Add excluded_search_path_prefixes setting
nvbn/thefuck pull request #1165
Opened 2021-02-04 21:17 UTC by stuartleeks

Allows filtering the paths used to search for commands
Can be useful to filter out `/mnt/` in WSL for performance

Running in WSL with default config:
```
DEBUG: Total took: 0:00:10.213128
```

Running in WSL with `excluded_search_path_prefixes = ['/mnt/']` in `settings.py`:

```
DEBUG: Total took: 0:00:00.617300
```

This provides an approach to solving #1036 without having to remove Windows paths from `PATH` (which breaks various WSL use-cases)

2021-02-17 15:15 UTC, stuartleeks commented
Just checking back to see whether there is anything I can do to help make this easier to review? Thanks!

2021-04-15 21:42 UTC, mjohnson159 commented
What would it take to get this pulled in?

2021-04-16 21:56 UTC, scorphus requested changes
Thanks for the valuable contribution and for a very complete patch, @stuartleeks! Much appreciated! 👍

Please, consider my suggestions below.

2021-04-16 21:56 UTC, scorphus commented on tests/test_conf.py
> +                           'THEFUCK_EXCLUDED_SEARCH_PATH_PREFIXES': '/mnt/'})
```suggestion
                           'THEFUCK_EXCLUDED_SEARCH_PATH_PREFIXES': '/media/:/mnt/'})
```

2021-04-16 21:56 UTC, scorphus commented on tests/test_conf.py
> +        assert settings.excluded_search_path_prefixes == ['/mnt/']
```suggestion
        assert settings.excluded_search_path_prefixes == ['/media/', '/mnt/']
```

2021-04-16 21:56 UTC, scorphus commented on tests/test_utils.py
> +        assert call(path.split(pathsep)[0]) in Path_mock.mock_calls
```suggestion
        path_list = path.split(pathsep)
        assert call(path_list[-1]) not in Path_mock.mock_calls
        assert all(call(p) in Path_mock.mock_calls for p in path_list[:-1])
```

2021-04-16 21:56 UTC, scorphus commented on thefuck/utils.py
> +    return True
```suggestion
    return not any(path.startswith(x) for x in settings.excluded_search_path_prefixes)
```

2021-04-16 21:56 UTC, scorphus commented on thefuck/utils.py
> +            for path in os.environ.get('PATH', '').split(os.pathsep) if include_path_in_search(path)
```suggestion
            for path in os.environ.get('PATH', '').split(os.pathsep)
            if include_path_in_search(path)
```

2021-04-16 22:02 UTC, scorphus commented on thefuck/utils.py
> +    return True
As soon as support to Python 2 is dropped, that line can read like this:

```python
    return not any(map(path.startswith, settings.excluded_search_path_prefixes))
```

2021-04-17 06:30 UTC, stuartleeks commented
Thanks for the review @scorphus! I've included your suggestions and rebased on latest `master`

However, I notice that the automated checks are failing on python 2.7 at what looks to be the install stage. I'm not sure how the changes made would have caused this and have just tested installing on 2.7.17 locally and it seemed to work fine (unit tests all pass locally on 2.7.17, too). If you have any pointers for investigating further that would be greatly appreciated!

2021-04-17 16:05 UTC, scorphus commented
Glad you're still on it, @stuartleeks. Sorry for the delay.

I wonder why `pip` is installing decorator 5.x for Python 2.7. It should install 4.4.2 instead. Anyway, I didn't investigate too much into that issue. Instead came up with #1187 that forces `decorator<5` for Python <= 2.7. Once 3.31 is released, this and other makeshifts will be removed.

I'll get #1187 merged soon. Then you're free to rebase on top of master again. Thanks in advance!

2021-04-17 16:19 UTC, stuartleeks commented
Ok, cool. I'll rebase again once #1187 is merged and hopefully this will be ready to go 😁
Thanks!

2021-04-18 20:32 UTC, stuartleeks commented
Rebased now that #1187 is merged and the tests are now passing - thanks @scorphus !

2021-04-19 23:35 UTC, mjohnson159 commented
can't wait to update with these changes implemented with 3.31. I can't believe me commenting here kicked off the attention this needed to finally get merged and now I don't have to worry about manually building these changes into every new release haha

2021-04-20 14:51 UTC, scorphus commented
Thanks for the update, @stuartleeks! I'll be merging this shortly!

@mjohnson159 Thanks for commenting and bringing it to my attention. We really need to get 3.31 out, right!? It's been a long time since the last release. Would you be willing to help me confirming fixes for some other Windows-related issues? That would be super helpful!

2021-04-21 17:41 UTC, scorphus approved these changes

2021-04-21 17:43 UTC, merged

2021-04-21 17:44 UTC, scorphus commented
Thanks for contributing, @stuartleeks! :heart: