Introducing the cd-cs feature
nvbn/thefuck pull request #1167
Opened 2021-02-14 01:17 UTC by s1ddly

I found in my usage that due to the proximity of the 's' and 'd' key, I would commonly type cs when I mean to say cd.
I am hoping to address that with this update to the rules.

2021-03-08 01:20 UTC, s1ddly commented
@scorphus have you had a chance to look at this yet?

2021-03-19 03:11 UTC, s1ddly commented
![FB_IMG_1616075794372](https://user-images.githubusercontent.com/51441497/111726364-ef99df00-88bc-11eb-9e7b-216bebe03207.jpg)

2021-03-19 04:26 UTC, BimboPolitics commented
Following this github is the best decision ive made all week

2021-03-19 15:07 UTC, scorphus approved these changes
Hey, @s1ddly 👋 🤣

Sorry for the delay! I was wondering if we could fix this [some other way](https://github.com/scorphus/thefuck/tree/typo-distance) — that being the outcome of a hackthon I mentored a couple weeks ago. But it looks like that will need a bit more working.

Thank you for your contribution!

2021-03-19 15:07 UTC, scorphus commented on thefuck/rules/cd_cs.py
> +# cs: command not found
Nit: can I suggest a more informative head comment?
```suggestion
# Redirects cs to cd when there is a typo
# Due to the proximity of the keys — d and s — this seems like a common typo
# ~ > cs /etc/
# cs: command not found
# ~ > fuck
# cd /etc/ [enter/↑/↓/ctrl+c]
# /etc >
```

2021-03-21 11:45 UTC, s1ddly commented
Hey Mate,

I found that some of the python 2.7 build test cases failed on this one.
It seems that it doesn't like the up and down arrows in the comment.
Are we good to proceed with the failed tests or should I remove the offending characters?

Thanks, Sid.

2021-03-21 13:04 UTC, scorphus requested changes

2021-03-21 13:04 UTC, scorphus commented on thefuck/rules/cd_cs.py
> +# Redirects cs to cd when there is a typo
This should fix it:

```suggestion
# -*- encoding: utf-8 -*-

# Redirects cs to cd when there is a typo
```

2021-03-22 09:36 UTC, s1ddly commented
Looks like that fixed it.
Thats a pretty useful trick, I'll be sure to remember that for my future projects :)

2021-03-22 19:52 UTC, scorphus approved these changes

2021-03-22 19:55 UTC, merged

2021-03-22 19:56 UTC, scorphus commented
Thanks, @s1ddly!