~[Doc] Add Uninstall instructions
nvbn/thefuck pull request #1171
Opened 2021-03-03 18:04 UTC by Rom1deTroyes

As we need the package and to modify the shell config, users could have a pain in the ass when it comes to retire *The Fuck* from the system.
You can see this contribution as Vaseline in your shell.

2021-03-03 18:05 UTC, Rom1deTroyes commented
Close #455 definitely (I hope ?)

2021-06-30 12:19 UTC, scorphus requested changes

2021-06-30 12:19 UTC, scorphus commented on README.md
> +
```suggestion
```

2021-06-30 12:19 UTC, scorphus commented on README.md
> +To remove *The Fuck*, reverse the installation process :
```suggestion
To remove *The Fuck*, reverse the installation process:
```

2021-06-30 12:20 UTC, scorphus approved these changes
Thanks, @Rom1deTroyes 👍

2021-06-30 12:20 UTC, merged