Adding devcontainer and new rule for main-master
nvbn/thefuck pull request #1184
Opened 2021-04-06 13:54 UTC by storey247

Love the tool, wanted to contribute and here is the result :)

- Added a [VSCode devcontainer](https://code.visualstudio.com/docs/remote/containers) to help people get up and running with the repo quicker without needing to install any tooling or do any setup of venv
- Added a new rule to help when some repositories use `main` and some use `master` as the primary integration branch

Feedback welcome and thanks for the great tooling

2021-06-30 12:08 UTC, scorphus requested changes
Looking good!

Would you be willing to separate the two features into two different commits and — if it's not too much to ask — two different PR's?

Thanks!

2021-06-30 12:08 UTC, scorphus commented on thefuck/rules/git_main_master.py
> +    return "'master'" in command.output.lower() or "'main'" in command.output.lower()
Why is `.lower()` needed here?

2021-06-30 12:08 UTC, scorphus commented on thefuck/rules/git_main_master.py
> +        return command.script.replace("main", "master")
```suggestion
    return command.script.replace("main", "master")
```

2021-06-30 12:09 UTC, scorphus commented
Also, the fix for Python 2.7 tests is already on current `master`, would you please rebase on top of that? 🙂

2021-07-15 10:21 UTC, scorphus commented
Howdy @storey247! Thanks for contributing. I'd really love to read your comments on my suggestions above. I understand that you're probably busy with many stuff. But I thought I'd ping you 🙂

2021-07-16 14:17 UTC, storey247 commented
hi @scorphus thanks for all the feedback, yes I will action and get this PR split into two :smile: apologies for the delayed response, work is a bit crazy atm

2021-07-16 14:19 UTC, storey247 commented on .devcontainer/Dockerfile
> +RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
the devconainer.json file actually set the arg to false, so it's not getting installed, but as it's not necessary to have this I will remove 👍

2021-07-16 14:19 UTC, storey247 commented on .devcontainer/Dockerfile
> +# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
will clean up

2021-07-16 14:19 UTC, storey247 commented on .devcontainer/devcontainer.json
> +}
again, will clean

2021-07-16 21:13 UTC, scorphus commented
Awesome! I already split the commit into three, so no need to create another PR, I can merge the changes regarding the new rule and we leave this PR for the devcontainer addition. What do you think?

2021-07-17 08:08 UTC, storey247 commented
Amazing! Nice work! 👏👏👏

sounds like a plan, I’ll rebase this on Monday when the work is merged and I’ll tidy up the container so it’s nice and trim. 

Thanks @scorphus

2021-07-18 13:04 UTC, scorphus commented
There you go, @storey247. Sorry for the extra noise. To continue your work, I'd suggest you force-resetting to the `main_master` branch on your remote, that way you'll have exactly what this PR currently has. Please don't hesitate to ask me for help with that.

2021-07-19 18:25 UTC, storey247 commented
@scorphus I have now rebased my work from latest `master` and cleaned up the comments as discussed.

I also added some notes into the `Contribute.md` to help people get up and running with the devcontainer setup if required.

Hopefully now this work can be merged in too. Let me know if there is anything else you need me to look at

2021-07-19 18:25 UTC, storey247 commented on .devcontainer/Dockerfile
> +RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
I have also cleaned all this up as node is not required

2021-07-19 19:02 UTC, scorphus approved these changes
Thats super, @storey247! Thanks so much for hanging in! Please consider my suggestion below.

2021-07-19 19:21 UTC, storey247 commented on .devcontainer/devcontainer.json
> +			"VARIANT": "3.9"
yes you are correct, the ARG will be overridden by the value passed in the `devcontainer.json` and acts like a fallback default. Will set the `VARIANT` to be 3 as suggested

2021-07-19 19:24 UTC, storey247 commented on .devcontainer/devcontainer.json
> +			"VARIANT": "3.9"
done and sync'd to remote

2021-07-19 19:25 UTC, storey247 commented
> Thats super, @storey247! Thanks so much for hanging in! Please consider my suggestion below.

Feedback actions, just waiting on the builds and then will merge 👍

2021-07-19 20:35 UTC, scorphus approved these changes
Thanks, @storey247! That's a great contribution!

Also, thanks for the new `git_main_master` rule! 🙌

2021-07-19 20:35 UTC, scorphus commented on .devcontainer/devcontainer.json
> +		}
```suggestion
		"context": ".."
```
Let's remove that redundancy 🙂

2021-07-19 20:35 UTC, scorphus commented on .devcontainer/devcontainer.json
> +	"settings": {
```suggestion
	"settings": {
```

2021-07-19 20:35 UTC, scorphus commented on .devcontainer/devcontainer.json
> +	"postCreateCommand": "pip3 install -r requirements.txt && python3 setup.py develop",
```suggestion
	"postCreateCommand": "pip3 install -r requirements.txt && python3 setup.py develop"
```

2021-07-19 20:47 UTC, merged