#1282 git misspelled
nvbn/thefuck pull request #1292
Opened 2022-05-03 19:31 UTC by NikosKakonas

The function git_support can not be useful if a command has the word "git" misspelled.
The purpose of this rule is to unfuck the commands like: gti commit -m 'message'.
Without this rule, for example, if you try to unfuck this command the result will be:
git commit -m message. This means that the quotation marks do not return. #1282

This rule is generally useful for every git command, in which the word git is misspelled.

I have also run some tests!

2022-05-04 18:07 UTC, scorphus approved these changes
This could be helpful for cases `no_command` isn't able to fix. Please, consider my suggestions below.

2022-05-04 18:07 UTC, scorphus commented on tests/rules/test_git_misspenlled.py
> +    assert get_new_command(Command(script, output)) == new_command
Please, correct the name of this file.

Also, could you add `test_not_match` for cases where the rule does not match?

2022-05-04 22:52 UTC, NikosKakonas commented
I made test_not_match fucntion. I hope that now it is better!

2022-05-18 12:16 UTC, djh82 commented
It feels like rather than solving this specifically for the git command, it might be prudent to solve the issue in the no_command rule?

2022-05-19 21:41 UTC, NikosKakonas commented
Thank you a lot for the review! Is this commit satisfying for the project?

2022-05-29 15:55 UTC, djh82 commented
You'll probably want to revert the readme change and add some further tests for no_command?

2022-06-08 22:08 UTC, scorphus commented
Regarding the failure, please check #1310.

2022-06-10 04:51 UTC, NikosKakonas commented
@djh82 @scorphus
Are there any other mistakes of missing cases?

2022-06-10 14:38 UTC, NikosKakonas commented
I believe that now it is correct!

2022-06-10 23:31 UTC, scorphus requested changes

2022-06-11 17:15 UTC, scorphus commented
@NikosKakonas, could you please rebase this on top of current `master`? Thanks!

2022-06-13 09:42 UTC, NikosKakonas commented
> @NikosKakonas, could you please rebase this on top of current `master`? Thanks!

![image](https://user-images.githubusercontent.com/72870195/173325953-86a9678f-fc2e-48c2-95f3-d3a3c3f27691.png)

@scorphus Could you please help me with this message?

2022-06-13 09:50 UTC, NikosKakonas commented
@scorphus  Is it now okay? Thanks!

2022-06-13 16:41 UTC, NikosKakonas commented
@scorphus Is it okay for merging?

2022-06-13 21:25 UTC, scorphus approved these changes
Thanks, @NikosKakonas! 👍

2022-06-13 21:29 UTC, merged

2022-06-14 06:04 UTC, NikosKakonas commented
The plesure is main!

2023-10-30 19:15 UTC, alaycock commented
@nkakonas does this justify a new release? This has been bugging me for a bit.

2024-10-16 20:51 UTC, alaycock commented
@scorphus could you cut a new release for this?