README->Installation: Clarify that the alias is really needed
nvbn/thefuck pull request #613
Opened 2017-03-14 23:02 UTC by rubo77

2017-03-15 00:16 UTC, nvbn commented
In newer versions when alias isn't configured it works like:
```bash
➜  fuck
Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.zshrc and apply changes with source ~/.zshrc or restart your shell.
Or run fuck second time for configuring it automatically.
More details - https://github.com/nvbn/thefuck#manual-installation
```

2017-03-23 02:51 UTC, sphvn commented
@nvbn, the current version displaying the message like you posted above is more than enough.

👍 on just closing this in my opinion.

2017-04-21 08:44 UTC, matkoniecz commented
Bold is overkill, but changing "should" to "must" in my opinion is a good clarification.

2021-07-29 19:33 UTC, scorphus requested changes

2021-07-29 19:33 UTC, scorphus commented on README.md
> +**Now you must place this command in your `.bash_profile`, `.bashrc`, `.zshrc` or other startup script:**
```suggestion
You must place this command in your `.bash_profile`, `.bashrc`, `.zshrc` or other startup script:
```

2021-07-29 20:13 UTC, scorphus commented
Actually, the section of REAME.md related to this PR has changed and is clear enough, IMO. Closing this PR for now.

2021-07-29 20:13 UTC, closed without merging